# Generated by Django 2.1.5 on 2021-08-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210804_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(blank=True, default='movie_icon.png', upload_to='movie_thumbnails/'),
        ),
    ]
