# Generated by Django 2.1.5 on 2021-08-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210804_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='populateimage',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
