# Generated by Django 2.1.5 on 2021-08-05 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_movie_populateimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='populateimage',
        ),
    ]
